"""Inventory of quarantined files belonging to a challenge submission.

File bytes live in restricted storage. The ingestion service must calculate
hashes and sizes, validate paths/content, and freeze submitted inventories.
This model does not read, scan, move or delete physical files.
"""

from datetime import datetime, timezone
from typing import Optional

from sqlalchemy import CheckConstraint, DateTime, ForeignKey, Integer, String, Text, UniqueConstraint, text
from sqlalchemy.orm import Mapped, mapped_column, relationship

from db.orm import db


def utc_now():
    return datetime.now(timezone.utc)


class SubmissionFile(db.Model):
    __bind_key__ = "pond"
    __tablename__ = "submission_files"
    __table_args__ = (
        CheckConstraint("size_bytes >= 0", name="ck_submission_file_size"),
        CheckConstraint(
            "length(sha256) = 64 AND sha256 NOT GLOB '*[^0-9a-f]*'",
            name="ck_submission_file_sha256",
        ),
        CheckConstraint(
            "validation_status IN ('pending', 'passed', 'failed', 'review_required')",
            name="ck_submission_file_validation_status",
        ),
        UniqueConstraint("submission_id", "logical_path", name="uq_submission_file_path"),
        # Supports the forthcoming issue table's composite foreign key, which
        # prevents an issue from referring to another submission's file.
        UniqueConstraint("submission_id", "file_id", name="uq_submission_file_identity"),
    )

    file_id: Mapped[int] = mapped_column(Integer, primary_key=True)
    submission_id: Mapped[int] = mapped_column(
        ForeignKey("challenge_submissions.submission_id", ondelete="RESTRICT"), nullable=False
    )
    file_role: Mapped[str] = mapped_column(String(50), nullable=False)
    # A normalized package-relative identifier; never use directly as a host path.
    logical_path: Mapped[str] = mapped_column(Text, nullable=False)
    original_filename: Mapped[str] = mapped_column(Text, nullable=False)
    # Generated by the server. This design gives each revision its own objects.
    storage_key: Mapped[str] = mapped_column(Text, nullable=False, unique=True)
    size_bytes: Mapped[int] = mapped_column(Integer, nullable=False)
    sha256: Mapped[str] = mapped_column(String(64), nullable=False)
    detected_media_type: Mapped[Optional[str]] = mapped_column(String(100))
    validation_status: Mapped[str] = mapped_column(
        String(20), nullable=False, default="pending", server_default=text("'pending'")
    )
    validated_at: Mapped[Optional[datetime]] = mapped_column(DateTime(timezone=True))
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, default=utc_now,
        server_default=text("CURRENT_TIMESTAMP"),
    )

    submission: Mapped["ChallengeSubmission"] = relationship()
